/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
//import javax.media.*;

public class user_api extends javax.swing.JFrame {
    User user;
    int puntata;
    int saldo;
    int scommessa;
    
    
    /**
     * Creates new form user_api
     */
    public user_api() {
        initComponents();
    }
    public user_api(User d) {
        user = d;
        initComponents();
    }
    
    public void inserisci_saldo(){  
        saldo = Integer.parseInt(JOptionPane.showInputDialog(null, "Inserisci il saldo che vuoi puntare","saldo", JOptionPane.PLAIN_MESSAGE)); 
        jLabel_saldo.setText("SALDO: "+ saldo);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_punta1 = new javax.swing.JButton();
        jButton_punta2 = new javax.swing.JButton();
        jButton_punta5 = new javax.swing.JButton();
        jButton_punta10 = new javax.swing.JButton();
        jButton_punta25 = new javax.swing.JButton();
        jLabel_saldo = new javax.swing.JLabel();
        jLabel_puntata = new javax.swing.JLabel();
        jButton_spin = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_punta1.setText("1€");
        jButton_punta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_punta1ActionPerformed(evt);
            }
        });

        jButton_punta2.setText("2€");
        jButton_punta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_punta2ActionPerformed(evt);
            }
        });

        jButton_punta5.setText("5€");
        jButton_punta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_punta5ActionPerformed(evt);
            }
        });

        jButton_punta10.setText("10€");
        jButton_punta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_punta10ActionPerformed(evt);
            }
        });

        jButton_punta25.setText("25€");
        jButton_punta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_punta25ActionPerformed(evt);
            }
        });

        jLabel_saldo.setText("SALDO:");

        jLabel_puntata.setText("PUNTATA:");

        jButton_spin.setText("SPIN");
        jButton_spin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_spinActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\simon\\OneDrive\\Desktop\\RouletteGUI\\src\\main\\java\\Images\\num1.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_puntata, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jButton_punta1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_punta2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButton_punta5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButton_punta10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_punta25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jButton_spin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_puntata, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_punta1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_punta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_punta5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_punta10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_punta25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton_spin))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println("Hai cliccato il num1 ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_spinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_spinActionPerformed
        // TODO add your handling code here:Algoritmo ruota = new Algoritmo();
        Algoritmo ruota = new Algoritmo();
        saldo += ruota.Algoritmo(puntata, 1, scommessa);
        System.out.println("il saldo dopo lo spin= " + saldo);
        puntata = 0;
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));
    }//GEN-LAST:event_jButton_spinActionPerformed

    private void jButton_punta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_punta25ActionPerformed
        // TODO add your handling code here:
        puntata += 25;
        saldo = saldo - 25;
        System.out.println("puntata = " + puntata + "€");
        jLabel_saldo.setText("SALDO: "+ saldo);
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));
    }//GEN-LAST:event_jButton_punta25ActionPerformed

    private void jButton_punta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_punta10ActionPerformed
        // TODO add your handling code here:
        puntata += 10;
        saldo = saldo - 10;
        System.out.println("puntata = " + puntata + "€");
        jLabel_saldo.setText("SALDO: "+ saldo);
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));
    }//GEN-LAST:event_jButton_punta10ActionPerformed

    private void jButton_punta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_punta5ActionPerformed
        // TODO add your handling code here:
        puntata += 5;
        saldo = saldo - 5;
        System.out.println("puntata = " + puntata + "€");
        jLabel_saldo.setText("SALDO: "+ saldo);
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));
    }//GEN-LAST:event_jButton_punta5ActionPerformed

    private void jButton_punta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_punta2ActionPerformed
        // TODO add your handling code here:
        puntata += 2;
        saldo = saldo - 2;
        System.out.println("puntata = " + puntata + "€");
        jLabel_saldo.setText("SALDO: "+ saldo);
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));
    }//GEN-LAST:event_jButton_punta2ActionPerformed

    private void jButton_punta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_punta1ActionPerformed
        // TODO add your handling code here:
        puntata += 1;
        saldo = saldo - 1;
        System.out.println("puntata = " + puntata + "€");
        jLabel_saldo.setText("SALDO: "+ saldo);
        jLabel_puntata.setText("PUNTATA: " + Integer.toString(puntata));

    }//GEN-LAST:event_jButton_punta1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_api.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_api.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_api.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_api.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        user_api frame = new user_api();
        frame.inserisci_saldo();
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_punta1;
    private javax.swing.JButton jButton_punta10;
    private javax.swing.JButton jButton_punta2;
    private javax.swing.JButton jButton_punta25;
    private javax.swing.JButton jButton_punta5;
    private javax.swing.JButton jButton_spin;
    private javax.swing.JLabel jLabel_puntata;
    private javax.swing.JLabel jLabel_saldo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
